[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://odyexchange.cc/*"
  to = "https://odyexchange.cc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.odyexchange.cc/*"
  to = "https://odyexchange.cc/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build]
  publish = "dist"
  command = "npm run build"
